import { StyleSheet } from 'react-native';
import { colors } from '../../utils/colors';
import { widthPercentageToDP as wp, heightPercentageToDP as hp } from 'react-native-responsive-screen';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingTop: hp(6),
    backgroundColor: 'white',
  },
  scrollContainer: {
    flexGrow: 1,
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingTop: hp(9),
    paddingBottom: hp(2.5),
    gap: hp(1),
    width: wp('100%'),
    backgroundColor: 'red',
  },
  header: {
    width: '100%',
    alignItems: 'center',
    marginBottom: hp(2),
  },
  headerTitle: {
    marginTop: 0,
    fontWeight: '700',
    fontSize: 24,
    color: '#222',
    textAlign: 'center',
    lineHeight: 32,
  },
  formContainer: {
    width: '95%',
    alignSelf: 'center',
    marginTop: 0,
    marginBottom: 0,
  },
  inputContainer: {
    width: '100%',
    marginTop: 16,
    marginBottom: 0,
  },
  input: {
    width: '100%',
    backgroundColor: '#F7F8F9',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E8ECF4',
    paddingHorizontal: 18,
    paddingVertical: 14,
    fontSize: 14,
    color: '#222',
    marginBottom: 16,
  },
  inputError: {
    borderColor: '#FF3B30',
  },
  errorText: {
    color: '#FF3B30',
    fontSize: 12,
    marginTop: -12,
    marginBottom: 8,
    marginLeft: 4,
  },
  passwordInputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F7F8F9',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E8ECF4',
   // paddingHorizontal: 18,
    marginBottom: 8,
  },
  passwordInput: {
    flex: 1,
    fontSize: 14,
    color: '#222',
    paddingVertical: 14,
  },
  eyeIcon: {
    padding: 8,
  },
  forgotPassword: {
    alignSelf: 'flex-end',
    color: '#8391A1',
    fontSize: 13,
    marginBottom: 24,
  },
  btn: {
    width: '100%',
    paddingVertical: 16,
    backgroundColor: '#F9DC76',
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 8,
    marginBottom: 24,
  },
  btnDisabled: {
    opacity: 0.7,
  },
  btnText: {
    color: '#222',
    fontSize: 16,
    fontWeight: '700',
  },
  dividerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '90%',
    alignSelf: 'center',
    marginVertical: 24,
  },
  divider: {
    flex: 1,
    height: 1,
    backgroundColor: '#E8ECF4',
  },
  dividerText: {
    marginHorizontal: 12,
    color: '#8391A1',
    fontSize: 14,
    fontWeight: '500',
  },
  socialLoginContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '90%',
    alignSelf: 'center',
    marginTop: 0,
    marginBottom: 32,
  },
  socialIcon: {
    width: "45%",
    height: 64,
    borderRadius: 16,
    backgroundColor: '#F7F8F9',
    borderWidth: 1,
    borderColor: '#E8ECF4',
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 8,
  },
  registerLink: {
    alignSelf: 'center',
    marginTop: 0,
    marginBottom: 16,
  },
  registerText: {
    color: '#222',
    fontSize: 14,
    textAlign: 'center',
  },
  registerNow: {
    color: '#F9DC76',
    fontWeight: '700',
  },
  switchContainer: {
    flexDirection: 'row',
    backgroundColor: '#F5F5F5',
    borderRadius: 12,
     width: '100%',
     marginVertical: 20,
    position: 'relative',
    height: 48,
    overflow: 'hidden',
  },
  switchIndicator: {
    position: 'absolute',
    width: '50%',
    height: '100%',
    backgroundColor: '#F9DC76',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#F9DC76',
  },
  switchButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1,
    borderRadius: 10,
  },
  switchButtonActive: {
    backgroundColor: 'transparent',
  },
  switchText: {
    color: '#8391A1',
    fontSize: 13,
    fontWeight: '600',
    textAlign: 'center',
  },
  switchTextActive: {
    color: '#222',
    fontWeight: '700',
  },
}); 