import { I18nManager, StyleSheet, Platform } from 'react-native';
import { colors } from "../../utils/colors";
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from "react-native-responsive-screen";

export const styles = StyleSheet.create({
  // Modern Uber-like styles
  uberContainer: {
    flex: 1,
    backgroundColor: '#F8F8F8',
  },
  uberHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 24,
    paddingVertical: 16,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
  },
  uberHeaderButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#F5F5F5',
    justifyContent: 'center',
    alignItems: 'center',
  },
  uberHeaderContent: {
    flex: 1,
    marginLeft: 12,
  },
  uberHeaderTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: '#000',
    textAlign: 'center',
  },
  uberHeaderSpacer: {
    width: 40,
  },
  uberScrollView: {
    flex: 1,
  },
  uberProfileSection: {
    backgroundColor: '#fff',
    paddingHorizontal: 14,
    paddingVertical: 32,
    marginBottom: 16,
  },
  uberProfileImageContainer: {
    alignItems: 'center',
    marginBottom: 24,
  },
  uberProfileImageWrapper: {
    position: 'relative',
  },
  uberProfileImage: {
    width: 120,
    height: 120,
    borderRadius: 60,
    borderWidth: 4,
    borderColor: '#F0F0F0',
  },
  uberProfileImagePlaceholder: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: '#E0E0E0',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 4,
    borderColor: '#F0F0F0',
  },
  uberProfileImageInitials: {
    fontSize: 36,
    fontWeight: '700',
    color: '#666',
  },
  uberUploadingOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    borderRadius: 60,
    justifyContent: 'center',
    alignItems: 'center',
  },
  uberEditIconContainer: {
    position: 'absolute',
    bottom: 5,
    right: 5,
    backgroundColor: '#000',
    borderRadius: 18,
    width: 36,
    height: 36,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 3,
    borderColor: '#fff',
  },
  uberUserInfoContainer: {
    alignItems: 'center',
 
  },
  uberUserName: {
    fontSize: 28,
    fontWeight: '700',
    color: '#000',
    marginBottom: 16,
    textAlign: 'center',
  },
  uberUserDetails: {
    alignItems: 'center',
    gap:10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
  },
  uberInfoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F8F8F8',
    paddingHorizontal: 0,
    paddingVertical: 8,
    borderRadius: 20,
   flex:1,
    justifyContent: 'center',
  },
  uberUserEmail: {
    fontSize: 14,
    color: '#8E8E93',
    marginLeft: 8,
  },
  uberUserPhone: {
    fontSize: 14,
    color: '#8E8E93',
    marginLeft: 8,
  },
  uberStatsContainer: {
    flexDirection: 'row',
    backgroundColor: '#F8F8F8',
    borderRadius: 20,
    padding: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  uberStatItem: {
    flex: 1,
    alignItems: 'center',
  },
  uberStatIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  uberStatNumber: {
    fontSize: 20,
    fontWeight: '700',
    color: '#000',
    marginBottom: 4,
  },
  uberStatLabel: {
    fontSize: 12,
    color: '#8E8E93',
    textAlign: 'center',
  },
  uberStatDivider: {
    width: 1,
    backgroundColor: '#E0E0E0',
    marginHorizontal: 16,
  },
  uberMenuSection: {
    backgroundColor: '#fff',
    paddingHorizontal: 24,
    paddingVertical: 24,
    marginBottom: 16,
  },
  uberSectionTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: '#000',
  
  },
  uberMenuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
  },
  uberMenuItemLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  uberMenuIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#F8F8F8',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
  },
  uberMenuTextContainer: {
    flex: 1,
  },
  uberMenuItemTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#000',
    marginBottom: 4,
  },
  uberMenuItemDescription: {
    fontSize: 14,
    color: '#8E8E93',
  },
  uberActionSection: {
    paddingHorizontal: 24,
    paddingVertical: 16,
    gap: 12,
  },
  uberLogoutButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#000',
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  uberLogoutText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#fff',
    marginLeft: 8,
  },
  uberDeleteButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff',
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#FF3B30',
  },
  uberDeleteText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FF3B30',
    marginLeft: 8,
  },
  uberBottomSpacing: {
    height: Platform.OS === 'ios' ? 34 : 24,
  },

  // Profile Section Screens Styles
  uberMainContainer: {
    flex: 1,
  },
  uberSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 24,
    paddingVertical: 16,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
  },
  uberBackButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#F5F5F5',
    justifyContent: 'center',
    alignItems: 'center',
  },
  uberSectionSubtitle: {
    fontSize: 14,
    color: '#8E8E93',
    textAlign: 'center',
    marginTop: 4,
  },
  uberScrollContainer: {
    paddingBottom: 24,
  },
  uberFormSection: {
    backgroundColor: '#fff',
    marginHorizontal: 16,
    marginTop: 16,
    borderRadius: 16,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  uberSectionHeaderInline: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  uberSectionHeaderTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#000',
    marginLeft: 12,
  },

  // Input Styles
  uberInputContainer: {
    marginBottom: 20,
  },
  uberInputLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#000',
    marginBottom: 8,
  },
  uberInputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F8F8F8',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E0E0E0',
    paddingHorizontal: 16,
    minHeight: 56,
  },
  uberInputIconContainer: {
    marginRight: 12,
  },
  uberInput: {
    flex: 1,
    fontSize: 16,
    color: '#000',
    paddingVertical: 16,
    textAlign: I18nManager.isRTL ? 'right' : 'left',
  },
  uberInputDisabled: {
    backgroundColor: '#F0F0F0',
  },
  uberInputLockContainer: {
    marginLeft: 12,
  },
  uberInputError: {
    borderColor: '#FF3B30',
  },
  uberPhoneInput: {
    flex: 1,
    height: 56,
    paddingHorizontal: 0,
    backgroundColor: 'transparent',
    borderWidth: 0,
  },

  // Password Input Styles
  uberPasswordWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F8F8F8',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E0E0E0',
    paddingHorizontal: 16,
    minHeight: 56,
  },
  uberPasswordInput: {
    flex: 1,
    fontSize: 16,
    color: '#000',
    paddingVertical: 16,
    textAlign: I18nManager.isRTL ? 'right' : 'left',
  },
  uberPasswordToggle: {
    marginLeft: 12,
    padding: 4,
  },
  uberPasswordStrengthContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
  },
  uberPasswordStrengthBar: {
    flex: 1,
    height: 4,
    backgroundColor: '#E0E0E0',
    borderRadius: 2,
    marginRight: 12,
  },
  uberPasswordStrengthFill: {
    height: '100%',
    borderRadius: 2,
  },
  uberPasswordStrengthText: {
    fontSize: 12,
    fontWeight: '600',
  },

  // Error Styles
  uberErrorContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
  },
  uberErrorText: {
    fontSize: 14,
    color: '#FF3B30',
    marginLeft: 8,
    flex: 1,
  },

  // Notice Styles
  uberNoticeContainer: {
    flexDirection: 'row',
    backgroundColor: '#E3F2FD',
    borderRadius: 12,
    padding: 16,
    marginHorizontal: 16,
    marginTop: 16,
  },
  uberNoticeIconContainer: {
    marginRight: 12,
  },
  uberNoticeText: {
    fontSize: 14,
    color: '#1976D2',
    flex: 1,
    lineHeight: 20,
  },

  // Security Tips Styles
  uberSecurityTip: {
    flexDirection: 'row',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
  },
  uberSecurityTipIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#E3F2FD',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
  },
  uberSecurityTipContent: {
    flex: 1,
  },
  uberSecurityTipTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#000',
    marginBottom: 4,
  },
  uberSecurityTipDescription: {
    fontSize: 14,
    color: '#8E8E93',
    lineHeight: 20,
  },

  // Help Screen Styles
  uberHelpOption: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
  },
  uberHelpOptionIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
  },
  uberHelpOptionContent: {
    flex: 1,
  },
  uberHelpOptionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#000',
    marginBottom: 4,
  },
  uberHelpOptionDescription: {
    fontSize: 14,
    color: '#8E8E93',
  },

  // Contact Options Styles
  uberContactGrid: {
    gap: 12,
  },
  uberContactOption: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F8F8F8',
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: '#E0E0E0',
  },
  uberContactIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
  },
  uberContactContent: {
    flex: 1,
  },
  uberContactTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#000',
    marginBottom: 4,
  },
  uberContactSubtitle: {
    fontSize: 14,
    color: '#8E8E93',
  },

  // FAQ Styles
  uberFAQItem: {
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
  },
  uberFAQHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  uberFAQQuestion: {
    fontSize: 16,
    fontWeight: '600',
    color: '#000',
    marginLeft: 12,
    flex: 1,
  },
  uberFAQAnswer: {
    fontSize: 14,
    color: '#8E8E93',
    lineHeight: 20,
    marginLeft: 32,
  },

  // App Info Styles
  uberAppInfoContainer: {
    backgroundColor: '#F8F8F8',
    borderRadius: 12,
    padding: 16,
  },
  uberAppInfoItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
  },
  uberAppInfoLabel: {
    fontSize: 16,
    color: '#000',
    fontWeight: '500',
  },
  uberAppInfoValue: {
    fontSize: 16,
    color: '#8E8E93',
  },
  uberAppInfoDivider: {
    height: 1,
    backgroundColor: '#E0E0E0',
    marginVertical: 8,
  },

  // Action Button Styles
  uberActionContainer: {
    paddingHorizontal: 24,
    paddingVertical: 16,
    backgroundColor: '#fff',
    borderTopWidth: 1,
    borderTopColor: '#F0F0F0',
  },
  uberActionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#000',
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  uberActionButtonDisabled: {
    backgroundColor: '#8E8E93',
    opacity: 0.6,
  },
  uberActionButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#fff',
    marginLeft: 8,
  },

  // Legacy styles (keeping for compatibility)
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 16,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#E5E5E5',
  },
  drawerToggleButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#F5F5F5',
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerContent: {
    flex: 1,
    marginLeft: 12,
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: '#000',
    textAlign: 'center',
  },
  headerSpacer: {
    width: 40,
  },
  profileHeaderContainer: {
    position: 'relative',
    marginBottom: 20,
  },
  headerBackground: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 200,
    backgroundColor: colors.primary,
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
  },
  profileContent: {
    paddingTop: 40,
    paddingHorizontal: 20,
    alignItems: 'center',
  },
  profileImageContainer: {
    marginBottom: 20,
  },
  profileImageWrapper: {
    position: 'relative',
  },
  profileImage: {
    width: 120,
    height: 120,
    borderRadius: 60,
    borderWidth: 4,
    borderColor: '#fff',
  },
  profileImagePlaceholder: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: '#E0E0E0',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 4,
    borderColor: '#fff',
  },
  profileImageInitials: {
    fontSize: 36,
    fontWeight: '700',
    color: '#666',
  },
  uploadingOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    borderRadius: 60,
    justifyContent: 'center',
    alignItems: 'center',
  },
  editIconContainer: {
    position: 'absolute',
    bottom: 5,
    right: 5,
    backgroundColor: colors.primary,
    borderRadius: 18,
    width: 36,
    height: 36,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 3,
    borderColor: '#fff',
  },
  userInfoContainer: {
    alignItems: 'center',
    marginBottom: 30,
  },
  userName: {
    fontSize: 24,
    fontWeight: '700',
    color: '#fff',
    marginBottom: 12,
    textAlign: 'center',
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    minWidth: 200,
    justifyContent: 'center',
  },
  userEmail: {
    fontSize: 14,
    color: '#666',
    marginLeft: 8,
  },
  userPhone: {
    fontSize: 14,
    color: '#666',
    marginLeft: 8,
  },
  joinDate: {
    fontSize: 12,
    color: '#666',
    marginLeft: 8,
  },
  statsContainer: {
    flexDirection: 'row',
    backgroundColor: '#fff',
    borderRadius: 20,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 6,
    width: '100%',
  },
  statItem: {
    flex: 1,
    alignItems: 'center',
  },
  statNumber: {
    fontSize: 20,
    fontWeight: '700',
    color: '#000',
    marginTop: 8,
    marginBottom: 4,
  },
  statLabel: {
    fontSize: 12,
    color: '#666',
    textAlign: 'center',
  },
  statDivider: {
    width: 1,
    backgroundColor: '#E0E0E0',
    marginHorizontal: 16,
  },
  mainContainer: {
    flex: 1,
  },
  scrollContainer: {
    flexGrow: 1,
  },
  stepContainer: {
    flex: 1,
    paddingHorizontal: 20,
  },
  formContainer: {
    flex: 1,
    paddingTop: 20,
    gap: 20,
  },
  inputContainer: {
    width: '100%',
  },
  label: {
    fontSize: 16,
    fontWeight: '600',
    color: '#0c0c0c',
    marginBottom: 8,
  },
  input: {
    height: 64,
    borderWidth: 1,
    borderColor: '#E8ECF4',
    borderRadius: 8,
    paddingHorizontal: 15,
    marginBottom: 5,
    backgroundColor: '#F7F8F9',
    color: '#000',
  },
  passwordContainer: {
    height: 64,
    borderWidth: 1,
    borderColor: '#E8ECF4',
    borderRadius: 8,
    paddingHorizontal: 15,
    marginBottom: 10,
    backgroundColor: '#F7F8F9',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  passwordContainerError: {
    borderColor: '#FF3B30',
  },
  passwordInput: {
    flex: 1,
    fontSize: 16,
    height: '100%',
    color: '#000',
    textAlign:I18nManager.isRTL? "right":"left"
  },
  inputError: {
    borderColor: '#FF3B30',
  },
  errorText: {
    color: '#FF3B30',
    fontSize: 12,
    marginTop: -5,
    marginBottom: 10,
    marginLeft: 5,
  },
  buttonContainer: {
    paddingHorizontal: 24,
    paddingBottom: 24,
    backgroundColor: '#fff',
    borderTopWidth: 1,
    borderTopColor: '#E8ECF4',
    height: 120,
    justifyContent: 'center',
  },
  nextButton: {
    backgroundColor: '#0c0c0c',
    height: 64,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loginButtonDisabled: {
    backgroundColor: '#0c0c0c80',
  },
  nextButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  menuContainer: {
    marginTop: 20,
    paddingHorizontal: 20,
  },
  menuButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 15,
    paddingHorizontal: 20,
    backgroundColor: '#fff',
    borderRadius: 10,
    marginBottom: 10,
    borderWidth: 3,
    borderColor: '#ccc',
  },
  menuButtonText: {
    fontSize: 18,
    fontWeight: '600',
    color: '#333',

  },
  arrowIcon: {
    width: 20,
    height: 20,
    tintColor: '#0c0c0c',
  },
  logoutButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#0c0c0c',
    padding: 15,
    margin: 20,
    borderRadius: 10,
    
  },
  logoutIcon: {
    width: 20,
    height: 20,
    marginRight: 10,
  },
  logoutText: {
    fontSize: 16,
    fontWeight: '500',
    color: '#fff',
  },
  settingsButton: {
    position: "absolute",
    top: 20,
    right: 20,
  },
  statIcon: {
    width: 45,
    height: 45,
    marginBottom: 8,
  },
  statValue: {
    color: "#0c0c0c",
    fontSize: hp(2.2),
    fontWeight: "700",
    marginTop: 5,
    textAlign: 'center',
  },
  // Tab Navigation Styles
  tabBar: {
    backgroundColor: "#19191C",
    elevation: 0,
    shadowOpacity: 0,
    borderBottomWidth: 1,
    borderBottomColor: '#2A2A2A',
  },
  tabLabel: {
    textTransform: 'none',
    fontSize: hp(1.8),
    fontWeight: '600',
  },
  tabIndicator: {
    backgroundColor: '#0c0c0c',
    height: 3,
  },
  // Section Styles
  sectionContainer: {
    flex: 1,
   // padding: 20,
    backgroundColor: '#fff',
  },
  sectionTitle: {
    color: '#0c0c0c',
    fontSize: hp(2.2),
    fontWeight: '600',
    marginBottom: 20,
  },
  inputLabel: {
    color: '#000',
    fontSize: hp(1.8),
    marginBottom: 8,
  },
  saveButton: {
    backgroundColor: '#0c0c0c',
    padding: 15,
    borderRadius: 10,
    alignItems: 'center',
    marginTop: 20,
  },
  saveButtonDisabled: {
    backgroundColor: '#0c0c0c80',
    opacity: 0.7,
  },
  saveButtonText: {
    color: '#fff',
    fontSize: hp(1.8),
    fontWeight: '600',
  },
  // Modal Styles
  modalOverlay: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.6)",
  },
  modalContent: {
    width: "100%",
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    padding: 24,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  modalIconContainer: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: "#0c0c0c20",
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
  },
  modalTitle: {
    color: "#01050D",
    fontWeight: "700",
    fontSize: hp(2.4),
    marginBottom: 12,
    textAlign: 'center',
  },
  modalMessage: {
    fontSize: hp(1.8),
    color: "#666666",
    textAlign: "center",
    marginBottom: 24,
    lineHeight: 22,
  },
  modalButtons: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
  },
  modalButton: {
    flex: 1,
    padding: 16,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: 'center',
  },
  modalButtonPrimary: {
    backgroundColor: '#0c0c0c',
  },
  modalButtonSecondary: {
    backgroundColor: '#F5F5F5',
  },
  modalButtonText: {
    fontSize: hp(1.8),
    fontWeight: "600",
    color: "#01050D",
  },
  modalButtonTextSecondary: {
    color: "#666666",
  },
  // Help Section Styles
  helpOptionsContainer: {
    marginTop: 20,
    marginBottom: 10,
  },
  helpOption: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#0c0c0c',
    padding: 15,
    borderRadius: 10,
    marginBottom: 15,
    borderWidth: 2,
    borderColor: '#E0E0E0',
    borderRightWidth: 3,
    borderBottomWidth: 3,
    borderTopWidth: 1,
    borderLeftWidth: 1,
  },
  helpOptionText: {
    color: '#fff',
    fontSize: hp(1.8),
    marginLeft: 15,
    fontWeight: '600',
  },
  faqContainer: {
   // marginTop: 20,
  },
  faqTitle: {
    color: '#0c0c0c',
    fontSize: hp(2),
    fontWeight: '600',
    marginBottom: 15,
  },
  faqItem: {
    borderWidth:1,
   borderColor:'#E0E0E0',
    padding: 15,
    borderRadius: 10,
    marginBottom: 15,
  },
  faqQuestion: {
    color: '#000',
    fontSize: hp(1.8),
    fontWeight: '600',
    marginBottom: 8,
  },
  faqAnswer: {
    color: '#444',
    fontSize: hp(1.6),
    lineHeight: 22,
  },
  passwordInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    position: 'relative',
    flex:1
  },
  eyeIcon: {
    
    marginStart: 15,
     
    
    height:"100%",
    width:60,
    alignItems:"center",
    justifyContent:"center"
  },
  languageButtons: {
    width: '100%',
    gap: 10,
    marginBottom: 20,
  },
  languageButton: {
    width: '100%',
    padding: 15,
    borderRadius: 10,
    alignItems: 'center',
     borderWidth:1,
    borderColor:'#E0E0E0',
    flexDirection:'row',
  },
});
